version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - $PWD/mongo-data:/data/db
    ports:
      - 27017:27017
    networks:
      - mongo
  #--------------------------------------------------------------------
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    hostname: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    ports:
      - 8081:8081
    networks:
      - mongo
    links:
      - mongo
networks:
  mongo:
    name: mongo
    driver: bridge

