#
#
version: '3.7'
services:
  mongodb:
    image: mongo:latest
    hostname: mongodb
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: testdb
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    networks:
      default:
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo-data:/data/db
networks:
  default:
volumes:
  mongo-data:
